[package]
name = "pendulum"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = "0.25.1"
nalgebra = "0.32.5"
nannou = "0.19.0"
nannou_egui = "0.19.0"
